#######
# Compiled from data/pato/functions/entity_579.mcscript
# to .//data/pato/functions/entity_579/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard objectives add loop.entity_579_summon dummy
function pato:modalfiles/loop_entity_579_summon
