#######
# Compiled from functions/gui/craft/results.mcscript
# to .//data/pato/functions/gui/craft/enchants/stand_damage_clear.mcfunction
#
# Generated by Minecraft Script for 1.16
######
item replace entity @s container.4 with air
item replace entity @s container.12 with air
item replace entity @s container.13 with air
item replace entity @s container.14 with air
