#######
# Compiled from functions/gui/craft/results.mcscript
# to .//data/pato/functions/gui/craft/enchants/stand_damage.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @p netherite_sword{pato:{Enchantments:[{id:"pato:stand_damage",lvl:1}]}}