#######
# Compiled from functions/gui/craft/results.mcscript
# to .//data/pato/functions/gui/craft/enchants/stand_damage_clear.mcfunction
#
# Generated by Minecraft Script for 1.16
######
item replace entity @s container.13 with air
clear @s book 1
clear @s lapis_lazuli 16
clear @s arrow 1
