#######
# Compiled from pato/functions/events/bossbars.mcscript
# to .//data/pato/functions/events/raids/bossbar_counters.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score .ID pato.RaidID matches 1 run function pato:events/raids/raid_event1/bossbar_counter

