#######
# Compiled from functions/stands/sex_pistols/powers.mcscript
# to .//data/pato/functions/stands/sex_pistols/dismount.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=stands.sex_pistols] at @s run ride @e[tag=stands.sex_pistols,limit=1] dismount