#######
# Compiled from pato/functions/events/raid_event1.mcscript
# to .//data/pato/functions/events/raids/raid_event1/check_completion.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute unless entity @e[tag=pato.raid1] run function pato:events/raids/raid_event1/random_rewards

execute if score .Raid1Completion pato.Data matches 1 run schedule clear pato:events/raids/raid_event1/check_completion
execute unless score .Raid1Completion pato.Data matches 1 run schedule function pato:events/raids/raid_event1/check_completion 2s
