#######
# Compiled from pato/functions/events/raid_event1.mcscript
# to .//data/pato/functions/events/raids/raid_event1/kill_count.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only pato:events/raids/raid_event1/kill_count

scoreboard players add @s pato.rdEv1KillC 1