#######
# Compiled from functions/stands/yellow_blaze/summons.mcscript
# to .//data/pato/functions/stands/yellow_blaze/magma_cubes.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score yBlaze.tickSummon yBlaze.tickSummon matches ..200 run function pato:mcscript/while1