#######
# Compiled from data/pato/functions/main.mcscript
# to .//data/pato/functions/stands/yellow_blaze/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/pato/functions/main.mcscript
execute as @e[tag=stand.yellow_blaze,tag=stand.active] at @s run function pato:stands/yellow_blaze/magma_cubes