#######
# Compiled from data/pato/functions/event_counter.mcscript
# to .//data/pato/functions/events/counter/counter_24.mcfunction
#
# Generated by Minecraft Script for 1.16
######
title @a actionbar {"text": "PatoEvento en 24 segundos...","color": "green"}

# Extended from data/pato/functions/event_counter.mcscript
# to .//data/pato/functions/events/counter/counter_24.mcfunction
schedule function pato:events/counter/counter_23 1s
