#######
# Compiled from data/pato/functions/event_counter.mcscript
# to .//data/pato/functions/events/counter/counter_activate.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tellraw @s {"text": "Activando contador...","color": "yellow"}
tellraw @a {"text": "El evento empezará en 1 minuto...","color": "gold"}
tellraw @a {"text": "PRIMER AVISO","color": "red"}
summon armor_stand ~ ~ ~ {Invisible:true,NoGravity:true,Invulnerable:true,Tags:["pato.point"]}
schedule function pato:events/counter/counter_30 30s