#######
# Compiled from data/pato/functions/entity_579.mcscript
# to .//data/pato/functions/modalfiles/loop_entity_579_summon.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players add loop.entity_579_summon loop.entity_579_summon 1
execute if score loop.entity_579_summon loop.entity_579_summon matches 200.. as @a at @s unless entity @e[tag=entity_579] if predicate pato:chance_579 run function pato.summon:entity_579
execute if score loop.entity_579_summon loop.entity_579_summon matches 200.. run scoreboard players reset loop.entity_579_summon loop.entity_579_summon
