#######
# Compiled from functions/stands/dark_ravager/powers.mcscript
# to .//data/pato/functions/stands/dark_ravager/super.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=pato.stand, tag=stand.active, tag=stand.dark_ravager] at @s run scoreboard players add dRav.tickSuper dRav.tickSuper 1
execute as @e[tag=pato.stand, tag=stand.active, tag=stand.dark_ravager] at @s if score dRav.tickSuper dRav.tickSuper matches 200.. run tellraw @a[distance=..15] {"text": "Dark Ravager. Cave Blindness!", "color": "red"}
execute as @e[tag=pato.stand, tag=stand.active, tag=stand.dark_ravager] at @s if score dRav.tickSuper dRav.tickSuper matches 200.. run summon silverfish ~ ~ ~
execute as @e[tag=pato.stand, tag=stand.active, tag=stand.dark_ravager] at @s if score dRav.tickSuper dRav.tickSuper matches 200.. run effect give @a[distance=2.1..15] darkness 4 3 true
execute as @e[tag=pato.stand, tag=stand.active, tag=stand.dark_ravager] at @s if score dRav.tickSuper dRav.tickSuper matches 200.. run scoreboard players reset dRav.tickSuper dRav.tickSuper