#######
# Compiled from data/pato/functions/main.mcscript
# to .//data/pato/functions/stands/dark_ravager/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/pato/functions/main.mcscript
execute as @e[tag=stand.dark_ravager,tag=stand.active] at @s run function pato:stands/dark_ravager/super