#######
# Compiled from data/pato/functions/item_functions.mcscript
# to .//data/pato/functions/food/eskimo.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only pato:predicates/consume_eskimo
effect give @s saturation 1 5 true
