#######
# Compiled from data/pato/functions/item_functions.mcscript
# to .//data/pato/functions/food/watermelon_water.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only pato:predicates/consume_watermelon_water
effect give @s saturation 1 3 true
