#######
# Compiled from data/pato/functions/load.mcscript
# to .//data/pato/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
ler!
scoreboard objectives add pato.demo dummy
scoreboard objectives add pato.ticks dummy
scoreboard objectives add pato.seconds dummy
scoreboard objectives add pato.raidEv1Memb dummy
scoreboard objectives add pato.raidLevel dummy
scoreboard objectives add pato.RaidID dummy
scoreboard objectives add pato.currntEvent dummy
scoreboard objectives add pato.Craft dummy
scoreboard objectives add pato.joins dummy
scoreboard objectives add pato.Data dummy

# Extended from pato/functions/events/raid_event1.mcscript
# to data/pato/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add pato.rdEv1KillC dummy
