#######
# Compiled from functions/stands/yellow_blaze/summons.mcscript
# to data/pato/functions/mcscript/while1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score yBlaze.tickSummon yBlaze.tickSummon matches ..199 run scoreboard players add yBlaze.tickSummon yBlaze.tickSummon 1
execute unless score yBlaze.tickSummon yBlaze.tickSummon matches ..199 run execute as @s[tag=stand.active] at @s run summon magma_cube ~ ~ ~
execute unless score yBlaze.tickSummon yBlaze.tickSummon matches ..199 run execute as @s[tag=stand.active] at @s run effect give @a[2.1..15] slowness 4 3
execute unless score yBlaze.tickSummon yBlaze.tickSummon matches ..199 run execute as @s[tag=stand.active] at @s run effect give @s regeneration 4 4
execute unless score yBlaze.tickSummon yBlaze.tickSummon matches ..199 run execute as @s[tag=stand.active] at @s run tellraw @a[distance=..15] {"text": "Yellow Blaze. Infernal Cube!", "color": "red"}
execute unless score yBlaze.tickSummon yBlaze.tickSummon matches ..199 run scoreboard players reset yBlaze.tickSummon yBlaze.tickSummon
execute if entity @s[tag=!mcscriptStop] if score yBlaze.tickSummon yBlaze.tickSummon matches ..200 run function pato:mcscript/while1
tag @s[tag=mcscriptStop] remove mcscriptStop
