#######
# Compiled from data/pato/functions/item_functions.mcscript
# to .//data/pato/functions/stand_arrow/target_selector.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=item,nbt={Item:{id:"minecraft:arrow",tag:{pato:{id:3}}}}] at @s if entity @p[distance=..5] run tag @p[distance=..5] add pato.standOwner
execute as @e[type=item,nbt={Item:{id:"minecraft:arrow",tag:{pato:{id:3}}}}] at @s if entity @p[distance=..5] as @p[tag=pato.standOwner] at @s run function pato.summon:random_stand
execute as @e[type=item,nbt={Item:{id:"minecraft:arrow",tag:{pato:{id:3}}}}] at @s if entity @p[distance=..5] run kill