#######
# Compiled from pato/functions/stands/generic.mcscript
# to .//data/pato/functions/stands/attack_check.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a at @s unless entity @s[advancements={pato:predicates/player_hurt_entity=true}] run function pato:stands/deactivate_stand
execute as @a at @s if entity @s[advancements={pato:predicates/player_hurt_entity=true}] run function pato:stands/keep_stand
