#######
# Compiled from pato/functions/stands/generic.mcscript
# to .//data/pato/functions/stands/keep_stand.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a at @s run advancement revoke @s only pato:predicates/player_hurt_entity
execute as @a at @s run schedule function pato:stands/attack_check 5s
