#######
# Compiled from data/pato/functions/misc.mcscript
# to .//data/pato/functions/counter_trigger.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tellraw @s {"text": "[ACTIVAR CONTADOR]","color": "red","clickEvent": {"action": "run_command","value": "/function pato:events/counter/counter_activate"}}
