#######
# Compiled from data/pato/functions/join_system.mcscript
# to .//data/pato/functions/first_join.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s wooden_pickaxe
give @s wooden_axe
give @s cooked_beef 4
