#######
# Compiled from data/pato/functions/join_system.mcscript
# to .//data/pato/functions/player_join.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players add @s pato.joins 1
title @s title {"text": "PatoLand","color": "yellow"}
title @s subtitle {"text": "¡Bienvenido al servidor!","color": "gold"}
title @s actionbar [{"score":{"name": "@s","objective": "pato.joins"},"color": "dark_green"},{"text": " Joins","color": "green"}]