#######
# Compiled from pato/functions/enchants/registries.mcscript
# to .//data/pato/functions/enchants/detect.mcfunction
#
# Generated by Minecraft Script for 1.16
######
AddEnchantment(stand_damage, default)