#######
# Compiled from pato/functions/enchants/registries.mcscript
# to .//data/pato/functions/enchants/detect.mcfunction
#
# Generated by Minecraft Script for 1.16
######
## Encantamiento: stand_damage | Condición: player_hurt_entity | Slot: weapon.mainhand
scoreboard objectives add stand_damage.default dummy
scoreboard objectives add ench.stand_damage.maxLvl dummy
scoreboard objectives add ench.stand_damage.lvl dummy
execute as @a at @s if entity @s[advancements={pato:ench/stand_damage/player_hurt_entity=true}] run scoreboard players set @s stand_damage.default 1
execute as @a[predicate=pato:enchants/stand_damage] at @s store result score @s ench.stand_damage.lvl run data get entity @s SelectedItem.tag.pato.Enchantments.[0].lvl
execute as @a[predicate=pato:enchants/stand_damage] at @s if entity @s[predicate=pato:enchants/stand_damage_conds/player_hurt_entity] run function pato:enchants/stand_damage
execute as @a[predicate=pato:enchants/stand_damage] at @s run item modify entity @s weapon.mainhand pato:enchants/stand_damage