#######
# Compiled from pato/functions/enchants/enchantment_mechanics.mcscript
# to .//data/pato/functions/enchants/stand_damage.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a[predicate=pato:enchants/stand_damage,predicate=pato:enchants/stand_damage_conds/player_hurt_entity] at @s if score @s ench.stand_damage.lvl matches 1 run damage @e[tag=pato.stand,distance=..3,limit=1,tag=stand.active] 3 player_attack
execute as @a[predicate=pato:enchants/stand_damage,predicate=pato:enchants/stand_damage_conds/player_hurt_entity] at @s unless score @s ench.stand_damage.lvl matches 1 if score @s ench.stand_damage.lvl matches 2 run damage @e[tag=pato.stand,distance=..4,limit=1,tag=stand.active] 4 player_attack
execute as @a[predicate=pato:enchants/stand_damage,predicate=pato:enchants/stand_damage_conds/player_hurt_entity] at @s unless score @s ench.stand_damage.lvl matches 1 unless score @s ench.stand_damage.lvl matches 2 if score @s ench.stand_damage.lvl matches 3 run damage @e[tag=pato.stand,distance=..5,limit=1,tag=stand.active] 5 player_attack
execute as @a[predicate=pato:enchants/stand_damage,predicate=pato:enchants/stand_damage_conds/player_hurt_entity] at @s unless score @s ench.stand_damage.lvl matches 1 unless score @s ench.stand_damage.lvl matches 2 unless score @s ench.stand_damage.lvl matches 3 if score @s ench.stand_damage.lvl matches 4 run damage @e[tag=pato.stand,distance=..6,limit=1,tag=stand.active] 6 player_attack
execute as @a[predicate=pato:enchants/stand_damage,predicate=pato:enchants/stand_damage_conds/player_hurt_entity] at @s unless score @s ench.stand_damage.lvl matches 1 unless score @s ench.stand_damage.lvl matches 2 unless score @s ench.stand_damage.lvl matches 3 unless score @s ench.stand_damage.lvl matches 4 if score @s ench.stand_damage.lvl matches 5 run damage @e[tag=pato.stand,distance=..7,limit=1,tag=stand.active] 7 player_attack
execute as @a[predicate=pato:enchants/stand_damage,predicate=pato:enchants/stand_damage_conds/player_hurt_entity] at @s run advancement revoke @s only pato:ench/stand_damage/player_hurt_entity
execute as @a[predicate=pato:enchants/stand_damage,predicate=pato:enchants/stand_damage_conds/player_hurt_entity] at @s run scoreboard players reset @s stand_damage.default