#######
# Compiled from data/pato/functions/login_system.mcscript
# to .//data/pato/functions/login/changepass.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a if entity @s[tag=pato.registered] unless score @s changepass matches 0 if entity @s[tag=pato.enterNewKey] store result score @s pato.password run scoreboard players operation @s pato.password = @s changepass
execute as @a if entity @s[tag=pato.registered] unless score @s changepass matches 0 if entity @s[tag=pato.enterNewKey] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Contraseña actualizada con éxito. Tu nueva contraseña es ","color": "yellow"},{"score":{"name": "@s","objective": "pato.password"},"color": "gold"}]
execute as @a if entity @s[tag=pato.registered] unless score @s changepass matches 0 if entity @s[tag=pato.enterNewKey] run tag @s remove pato.enterNewKey
execute as @a if entity @s[tag=pato.registered] unless score @s changepass matches 0 unless entity @s[tag=pato.enterNewKey] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Ingresa tu nueva contraseña con ","color": "yellow"},{"text": "/trigger changepass set <contraseña>","color": "gold"}]
execute as @a if entity @s[tag=pato.registered] unless score @s changepass matches 0 unless entity @s[tag=pato.enterNewKey] run tag @s add pato.enterNewKey
execute as @a if entity @s[tag=pato.registered] unless score @s changepass matches 0 run scoreboard players reset @s changepass
