#######
# Compiled from data/pato/functions/login_system.mcscript
# to .//data/pato/functions/login/trigger_enable.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a if entity @s[tag=pato.registered] run scoreboard players enable @s login
execute as @a if entity @s[tag=pato.registered] run scoreboard players enable @s changepass
execute as @a if entity @s[tag=pato.registered] run function pato:login/login
execute as @a if entity @s[tag=pato.registered] run function pato:login/changepass
execute as @a unless entity @s[tag=pato.registered] run scoreboard players enable @s register
execute as @a unless entity @s[tag=pato.registered] run function pato:login/register