#######
# Compiled from pato/functions/events/hunger_games.mcscript
# to .//data/pato/functions/events/minigames/hunger_games/party_start.mcfunction
#
# Generated by Minecraft Script for 1.16
######
effect clear @a slow_falling
execute as @a at @s run fill ~5 ~-1 ~5 ~-5 ~-1 ~-5 air replace glass
title @a title {"text": "¡Vamos!","color": "green"}